[package]
name = "rust-api-warp-and-diesel"
version = "0.1.0"
authors = ["Szymon Gibala <szymon.gibala@sap.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
